
<!--//END HEADER -->

<section class="our-teachers">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="mb-5">Siswa Kami</h2>
                </div>
            </div>
            <div class="row" id="siswa-list">
                <?php foreach ($siswa as $row) : ?>
                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="admission_insruction">
                            <?php if(empty($row['siswa_photo'])): ?>
                                <img src="<?php echo base_url().'assets/images/blank.png';?>" class="img-fluid" alt="#">
                            <?php else: ?>
                                <img src="<?php echo base_url().'assets/images/'.$row['siswa_photo'];?>" class="img-fluid" alt="#">
                            <?php endif; ?>
                            <p class="text-center mt-3">
                                <span><?php echo $row['siswa_nama'];?></span><br>
                                <?php echo $row['kelas_nama'];?>
                            </p>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <!-- Pagination links will be dynamically generated by JavaScript -->
            <div class="row">
                <div class="col-md-12">
                    <ul class="pagination justify-content-center" id="pagination">
                        <!-- Pagination links will be dynamically added here -->
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!--//End Style 2 -->
<!--============================= FOOTER =============================-->
    <!--//END FOOTER -->
    <!-- jQuery, Bootstrap JS. -->
    <script src="<?php echo base_url().'theme/js/jquery.min.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/tether.min.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/bootstrap.min.js'?>"></script>
    <!-- Plugins -->
    <script src="<?php echo base_url().'theme/js/slick.min.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/waypoints.min.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/counterup.min.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/owl.carousel.min.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/validate.js'?>"></script>
    <script src="<?php echo base_url().'theme/js/tweetie.min.js'?>"></script>
    <!-- Subscribe -->
    <script src="<?php echo base_url().'theme/js/subscribe.js'?>"></script>
    <!-- Script JS -->
    <script src="<?php echo base_url().'theme/js/script.js'?>"></script>
    <script>
        $(document).ready(function() {
            var students = <?php echo json_encode($siswa); ?>; // Get all students data
            var perPage = 8; // Number of students per page
            var totalPages = Math.ceil(students.length / perPage); // Calculate total pages

            // Function to display students for a specific page
            function displayStudents(page) {
                var startIndex = (page - 1) * perPage;
                var endIndex = startIndex + perPage;
                var paginatedStudents = students.slice(startIndex, endIndex);

                var html = '';
                $.each(paginatedStudents, function(index, student) {
                    html += '<div class="col-xs-12 col-sm-6 col-md-3">';
                    html += '<div class="admission_insruction">';
                    if (student['siswa_photo']) {
                        html += '<img src="<?php echo base_url();?>assets/images/' + student['siswa_photo'] + '" class="img-fluid" alt="#">';
                    } else {
                        html += '<img src="<?php echo base_url();?>assets/images/blank.png" class="img-fluid" alt="#">';
                    }
                    html += '<p class="text-center mt-3">';
                    html += '<span>' + student['siswa_nama'] + '</span><br>';
                    html += student['kelas_nama'];
                    html += '</p>';
                    html += '</div></div>';
                });

                $('#siswa-list').html(html);
            }

            // Function to generate pagination links
            function generatePaginationLinks(totalPages) {
                var html = '';
                for (var i = 1; i <= totalPages; i++) {
                    html += '<li class="page-item"><a class="page-link" href="#" onclick="changePage(' + i + ')">' + i + '</a></li>';
                }
                $('#pagination').html(html);
            }

            // Initial display of first page
            displayStudents(1);
            generatePaginationLinks(totalPages);

            // Function to handle page change
            window.changePage = function(page) {
                displayStudents(page);
                // Optional: Add active class to current page link
                $('#pagination').find('li').removeClass('active');
                $('#pagination').find('li:eq(' + (page - 1) + ')').addClass('active');
            };
        });
    </script>
</body>

</html>
